"""Naprawiona migracja

Revision ID: 981211ce1d7e
Revises: 
Create Date: 2025-02-24 23:09:33.662237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981211ce1d7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_houses_name'), 'houses', ['name'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('desired_color', sa.String(length=50), nullable=True),
    sa.Column('detection_time', sa.Integer(), nullable=True),
    sa.Column('min_adc', sa.Integer(), nullable=True),
    sa.Column('max_adc', sa.Integer(), nullable=True),
    sa.Column('closet_brightness', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('WRGB_BLEXBOX', 'CCT_BLEBOX', 'WRGB_BLEXBOX_WITH_CLOSET', name='colortype'), nullable=True),
    sa.Column('use_motion_detector', sa.Boolean(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_houses_name'), table_name='houses')
    op.drop_table('houses')
    # ### end Alembic commands ###
