"""Dodanie mqtt_topic

Revision ID: ac6788b324c3
Revises: 981211ce1d7e
Create Date: 2025-03-06 22:43:46.821728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac6788b324c3'
down_revision: Union[str, None] = '981211ce1d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('mqtt_topic', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'mqtt_topic')
    # ### end Alembic commands ###
